#!/bin/bash

set -euo pipefail

root=$(cd -P -- "$(dirname -- "$0")/.." && pwd)
script="$root/bin/.local/bin/ssh-tailnet-config"
tailscale_fixture="$root/tests/fixtures/tailscale"
jq_bin=$(command -v jq)
test_home=$(mktemp -d "${TMPDIR:-/tmp}/funk-ssh-tailnet-test.XXXXXX")
trap 'rm -rf "$test_home"' EXIT

config_dir="$test_home/.ssh/config.d"
config_file="$test_home/.config/funk/ssh-tailnet.conf"
mkdir -p "$test_home/.config/funk"

# Every name here is built on RFC 2606's reserved example space, so no fixture
# carries a piece of anyone's real tailnet. The fixture's own node is greybird.
peers='blackbird midbird silverbird smolbird'
header='# Generated by funk ssh-tailnet-config; edits are overwritten.'
note='# Per-host User and Port come from ~/.config/funk/ssh-tailnet.conf'

fail() {
    printf 'ssh-tailnet-config test: %s\n' "$*" >&2
    exit 1
}

# Every Tailscale knob is optional here so a case can set one shell variable,
# call, and unset it, rather than each case restating the whole environment.
run_gen() {
    HOME="$test_home" \
        TAILSCALE="$tailscale_fixture" \
        JQ="$jq_bin" \
        FUNK_TEST_TAILSCALE_PEER_NAMES="${peer_names-$peers}" \
        FUNK_TEST_TAILSCALE_PEER_STATE="${peer_state-Online}" \
        FUNK_TEST_TAILSCALE_STATE="${backend_state-Running}" \
        FUNK_TEST_TAILSCALE_SELF_ONLINE="${self_online-1}" \
        FUNK_TEST_TAILSCALE_STATUS_FAIL="${status_fail-0}" \
        FUNK_TEST_TAILSCALE_INVALID_JSON="${invalid_json-0}" \
        FUNK_TEST_TAILSCALE_SUFFIX="${suffix-example-tailnet.ts.net}" \
        FUNK_TEST_TAILSCALE_RAW_LABEL="${raw_label-}" \
        FUNK_TEST_TAILSCALE_RAW_HOSTNAME="${raw_hostname-}" \
        "$script" "$@"
}

reset_state() {
    rm -rf "$test_home/.ssh"
    rm -f "$config_file"
}

# find compares permission bits exactly on both BSD and GNU, which BSD stat -f
# would not do portably and this suite runs everywhere.
mode_is() {
    [ -n "$(find "$1" -maxdepth 0 -perm "$2" 2>/dev/null)" ]
}

# A fresh account has no ~/.ssh at all, and every alias in the tailnet appears
# with the local account name, because Tailscale cannot say who to log in as.
reset_state
output=$(run_gen)
for host in greybird $peers; do
    [ -f "$config_dir/$host" ] || fail "no host file was generated for $host"
    printf '%s\n' "$output" | grep -Fx "wrote ~/.ssh/config.d/$host" >/dev/null \
        || fail "the run did not report writing $host"
done
expected=$(printf '%s\n' "$header" "$note" 'Host midbird' \
    '  Hostname midbird.example-tailnet.ts.net' "  User $(id -un)")
[ "$(cat "$config_dir/midbird")" = "$expected" ] \
    || fail "the generated host file is not the expected ssh_config stanza"
mode_is "$config_dir" 700 || fail "the generated host directory is not private"
mode_is "$config_dir/midbird" 600 || fail "the generated host file is not private"

# Converged state must be silent, because ./install runs this on every install.
output=$(run_gen)
[ -z "$output" ] || fail "an already-converged run was not silent"

# The overrides file is the only place per-host accounts and ports exist, and
# the whole point of it is that no repository carries it.
cat >"$config_file" <<'EOF'
# Local, untracked, and the only record of these accounts.
default_user=operator
user.smolbird=u0_a000
port.smolbird=8022
EOF
run_gen >/dev/null
expected=$(printf '%s\n' "$header" "$note" 'Host smolbird' \
    '  Hostname smolbird.example-tailnet.ts.net' '  Port 8022' '  User u0_a000')
[ "$(cat "$config_dir/smolbird")" = "$expected" ] \
    || fail "the per-host account and port overrides were not applied"
grep -Fx '  User operator' "$config_dir/midbird" >/dev/null \
    || fail "default_user did not replace the local account name"
if grep -q '^  Port ' "$config_dir/midbird"; then
    fail "a host with no port override was given one"
fi

# A device's OS hostname and its MagicDNS label drift apart the moment the
# hostname is not a DNS label -- an Android phone reports something like
# "MIKE's S22" and answers to nothing but its label. The alias has to follow the
# label, because the label is the name that resolves; following the hostname
# would drop the device entirely and then prune the file that names it.
reset_state
peer_names='blackbird smolbird'
raw_label=smolbird
raw_hostname="MIKE's S22"
run_gen >/dev/null
unset peer_names raw_label raw_hostname
[ -f "$config_dir/smolbird" ] \
    || fail "a device whose hostname is not a DNS label lost its MagicDNS alias"
grep -Fx '  Hostname smolbird.example-tailnet.ts.net' \
    "$config_dir/smolbird" >/dev/null \
    || fail "the alias does not point at the device's MagicDNS name"
[ "$(find "$config_dir" -maxdepth 1 -name 'MIKE*' | wc -l)" -eq 0 ] \
    || fail "an operating system hostname became a file name"

# The guard the whole design rests on: a file this command cannot prove it wrote
# is somebody's own work and is left exactly as it is.
reset_state
run_gen >/dev/null
hand_written=$(printf '%s\n' 'Host midbird' '  Hostname midbird.example.com' \
    '  User someone')
printf '%s\n' "$hand_written" >"$config_dir/midbird"
status=0
error=$(run_gen 2>&1 >/dev/null) || status=$?
[ "$status" -eq 0 ] || fail "a hand-written host file made the run fail"
[ "$(cat "$config_dir/midbird")" = "$hand_written" ] \
    || fail "a hand-written host file was overwritten"
printf '%s\n' "$error" \
    | grep -F 'refusing to overwrite ~/.ssh/config.d/midbird' >/dev/null \
    || fail "the refusal to overwrite was not reported"

# A leftover Stow link is the dangerous shape of that guard: writing through it
# would write into the repository this data just left.
printf 'Host silverbird\n' >"$test_home/linked-host"
ln -sf "$test_home/linked-host" "$config_dir/silverbird"
run_gen >/dev/null 2>&1
[ -L "$config_dir/silverbird" ] || fail "a symlinked host file was replaced"
[ "$(cat "$test_home/linked-host")" = 'Host silverbird' ] \
    || fail "the generator wrote through a symlink"

# A device that left the tailnet loses its generated file; nothing else in the
# directory is touched.
reset_state
run_gen >/dev/null
printf 'Host jumpbox\n  Hostname jump.example.com\n' >"$config_dir/jumpbox"
peer_names='blackbird silverbird smolbird'
output=$(run_gen)
unset peer_names
[ ! -e "$config_dir/midbird" ] \
    || fail "a device that left the tailnet kept its host file"
printf '%s\n' "$output" | grep -Fx 'removed ~/.ssh/config.d/midbird' >/dev/null \
    || fail "the removal was not reported"
[ -f "$config_dir/jumpbox" ] || fail "a hand-written host file was pruned"

# A broken link breaks every ssh invocation, not just its own host, so it is
# reported rather than passed over.
ln -s "$test_home/never-existed" "$config_dir/oldbird"
error=$(run_gen 2>&1 >/dev/null)
printf '%s\n' "$error" | grep -F 'oldbird is a broken symlink' >/dev/null \
    || fail "a broken symlink under config.d was not reported"
[ -L "$config_dir/oldbird" ] \
    || fail "a broken symlink was removed rather than reported"
rm -f "$config_dir/oldbird"

# Every way Tailscale can decline to answer leaves the existing files alone and
# exits EX_TEMPFAIL, which is what ./install reads as "run it again later".
reset_state
run_gen >/dev/null
before=$(cat "$config_dir/midbird")

expect_deferred() {
    local label="$1"
    local status=0

    run_gen >"$test_home/deferred-out" 2>"$test_home/deferred-err" || status=$?
    [ "$status" -eq 75 ] \
        || fail "$label did not defer with EX_TEMPFAIL (exit $status)"
    [ ! -s "$test_home/deferred-out" ] || fail "$label reported a change"
    [ "$(cat "$config_dir/midbird")" = "$before" ] \
        || fail "$label changed an existing host file"
    [ -f "$config_dir/smolbird" ] || fail "$label removed an existing host file"
}

backend_state=NeedsLogin
expect_deferred 'a signed-out Tailscale'
unset backend_state

backend_state=Stopped
expect_deferred 'a stopped Tailscale'
unset backend_state

self_online=0
expect_deferred 'an offline local node'
unset self_online

status_fail=1
expect_deferred 'an unreachable daemon'
unset status_fail

invalid_json=1
expect_deferred 'an invalid daemon response'
unset invalid_json

# No MagicDNS means no qualified name for any device, which would otherwise
# leave an empty device list -- and an empty list must never prune the machine's
# entire ssh configuration.
suffix=''
expect_deferred 'a tailnet with no MagicDNS names'
error=$(run_gen 2>&1 >/dev/null) || true
printf '%s\n' "$error" | grep -F 'no usable devices' >/dev/null \
    || fail "an empty device list was not distinguished"
unset suffix

# A shared tailnet carries other people's devices, and they name them. A name
# that is not a plain DNS label never becomes a path.
reset_state
peer_names='blackbird ../evil'
error=$(run_gen 2>&1 >/dev/null)
unset peer_names
[ ! -e "$test_home/.ssh/evil" ] \
    || fail "a device name escaped ~/.ssh/config.d"
[ -f "$config_dir/blackbird" ] \
    || fail "one unusable device name stopped the usable ones"
printf '%s\n' "$error" | grep -F 'not usable as a file name' >/dev/null \
    || fail "the unusable device name was not reported"

# Two devices answering to one short name cannot be told apart, so neither is
# written and the existing file is left rather than deleted.
reset_state
run_gen >/dev/null
before=$(cat "$config_dir/greybird")
peer_names='greybird blackbird'
error=$(run_gen 2>&1 >/dev/null)
unset peer_names
printf '%s\n' "$error" | grep -F 'ambiguous device name greybird' >/dev/null \
    || fail "an ambiguous device name was not reported"
[ "$(cat "$config_dir/greybird")" = "$before" ] \
    || fail "an ambiguous device name rewrote its host file"

# ssh applies Include before anything else, so a bad value would break every
# connection on the machine. It stops at the configuration file instead.
reset_state
printf 'port.smolbird=notaport\n' >"$config_file"
status=0
run_gen >/dev/null 2>&1 || status=$?
[ "$status" -eq 1 ] || fail "a malformed port override was accepted"
[ ! -d "$config_dir" ] || fail "a malformed override still wrote host files"

printf 'user.smolbird=two words\n' >"$config_file"
status=0
run_gen >/dev/null 2>&1 || status=$?
[ "$status" -eq 1 ] || fail "a malformed account override was accepted"
rm -f "$config_file"

# --check answers "what would this do" without creating anything.
reset_state
output=$(run_gen --check)
[ ! -d "$config_dir" ] || fail "--check created the host directory"
printf '%s\n' "$output" \
    | grep -Fx 'would write ~/.ssh/config.d/blackbird' >/dev/null \
    || fail "--check did not report the files it would write"

# An offline device is still a name worth having in ssh_config.
reset_state
peer_state=Offline
run_gen >/dev/null
unset peer_state
for host in $peers; do
    [ -f "$config_dir/$host" ] || fail "an offline device lost its host file"
done

if run_gen --nonsense >/dev/null 2>&1; then
    fail "an unknown option was accepted"
fi
