add_newline = false
scan_timeout = 500

[package]
disabled = true

[bun]
disabled = true

[python]
disabled = true

[git_commit]
disabled = false
only_detached = false
tag_disabled = true
format = '[\($hash\)]($style) '
