# Window splitting
unbind %
bind | split-window -h -c '#{pane_current_path}'
unbind '"'
bind _ split-window -v -c '#{pane_current_path}'

# Splitting without prefix (works on Termux where Ctrl+Space fails)
bind -n M-'\' split-window -h -c '#{pane_current_path}'
bind -n M-'-' split-window -v -c '#{pane_current_path}'
