#!/bin/bash

set -u

if [ -n "${FUNK_TEST_BUN_LOG:-}" ]; then
    {
        printf 'bun-stub'
        printf ' <%s>' "$@"
        printf '\n'
    } >>"$FUNK_TEST_BUN_LOG"
fi

exit "${FUNK_TEST_BUN_EXIT:-0}"
